### ISSUE TITLE
the product image is not appear

### ISSUE THREAD

**Issue by hajimohammadzaim** [khaleedasafry/2018_CO5027_1625154#3]
when click the product, the image is not showing up as per shown below:
![image](https://user-images.githubusercontent.com/36626308/39414794-59563c42-4c6e-11e8-9739-70a231c3486b.png)

**Comment by khaleedasafry** [comment]
problem fixed.

![image](https://user-images.githubusercontent.com/36612719/39623202-6dd020c8-4fc7-11e8-8b4d-8dc70b0bbe4f.png)

**Comment by hajimohammadzaim** [comment]
good
