### ISSUE TITLE
Contact Us dont have pin marks, no address and too closed between map and sign in 

### ISSUE THREAD

**Issue by hajimohammadzaim** [khaleedasafry/2018_CO5027_1625154#5]
- On map,  there is not pin marks.
- no address provided.
- between map and your sign in is too close . 

![image](https://user-images.githubusercontent.com/36626308/39414860-eff897b2-4c6e-11e8-8e34-56f3eb630176.png)

**Comment by khaleedasafry** [comment]
problems fixed

![image](https://user-images.githubusercontent.com/36612719/39622958-9eccd9ba-4fc6-11e8-9a82-b012cd504922.png)

**Comment by hajimohammadzaim** [comment]
On map, there is not pin marks. - done
no address provided. - done but to closed
between map and your sign in is too close - done
