### ISSUE TITLE
error when try sending email

### ISSUE THREAD

**Issue by hajimohammadzaim** [khaleedasafry/2018_CO5027_1625154#6]
there is error when i try send  to my email address as per shown below:

![image](https://user-images.githubusercontent.com/36626308/39414899-5832a2d2-4c6f-11e8-9d5a-1babf43352af.png)

**Comment by khaleedasafry** [comment]
- the email is only fixed for onlyschoolpurposes@gmail.com

**Comment by hajimohammadzaim** [comment]
actually its not about your email, you need to check at webconfig,what should be add.
